export enum ApplicationEventType {
  APPLICATION_SUBMITTED = 'application_submitted',
  STATUS_CHANGED = 'status_changed',
  STAGE_CHANGED = 'stage_changed',
  MESSAGE_SENT = 'message_sent',
  MESSAGE_RECEIVED = 'message_received',
  EMAIL_SENT = 'email_sent',
  EMAIL_RECEIVED = 'email_received',
  INTERVIEW_SCHEDULED = 'interview_scheduled',
  INTERVIEW_COMPLETED = 'interview_completed',
  INTERVIEW_CANCELED = 'interview_canceled',
  ASSESSMENT_ASSIGNED = 'assessment_assigned',
  ASSESSMENT_SUBMITTED = 'assessment_submitted',
  OFFER_RECEIVED = 'offer_received',
  OFFER_NEGOTIATED = 'offer_negotiated',
  OFFER_ACCEPTED = 'offer_accepted',
  OFFER_DECLINED = 'offer_declined',
  FEEDBACK_RECEIVED = 'feedback_received',
  FOLLOW_UP_SENT = 'follow_up_sent',
  REFERRAL_REQUESTED = 'referral_requested',
  NOTE_ADDED = 'note_added',
  REJECTED = 'rejected',
  WITHDRAWN = 'withdrawn',
  GHOSTED_MARKED = 'ghosted_marked',
  REOPENED = 'reopened',
  OTHER = 'other',
}

export enum EventChannel {
  EMAIL = 'email',
  LINKEDIN = 'linkedin',
  PHONE = 'phone',
  VIDEO_CALL = 'video_call',
  IN_PERSON = 'in_person',
  PLATFORM = 'platform',
  OTHER = 'other',
}
